openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/dswi6/TesteAPI/1.0.0
info:
  description: Descrição da API do projeto de Almoxarifado da disciplina DSWI6 - ADS IFSP-BRA.
  version: "1.0.0"
  title: Almoxarifado IFSP API
  contact:
    email: gustavo_veras@ifsp.edu.br
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: patrimonio
    description: Todos os endpoints sobre itens de patrimonio
paths:
  /patrimonio:
    get:
      summary: Busca todos os itens do inventário do almoxarifado
      tags:
        - patrimonio
      description: |
        O cliente não precisa passar nenhuma informação. Apenas acessando este endpoint, 
        ele obterá todos os itens.
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: Retorno de todos os itens de almoxarifado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemPatrimonio'
                example:
                  - patrimonio:  IFSP-BR-001
                    descricao: Armário de arquivos
                    itemTipo: 
                      nome: Escritorio
                      descricao: Materiais utilizados em escritório
                      imagem: https://images.unsplash.com/photo-1524820801657-fd59673fbb05?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1144&q=80
                    dataAquisicao: '2016-08-29T09:12:33.001Z'
                    precoAquisicao: 999.99
                    departamento: Informática
                    responsavel:  
                        prontuario: BP0910292
                        nome: Luiz Gustavo Véras
                        telefone: 408-867-5309
                        email: gustavo_veras@ifsp.edu.br
          
                  - patrimonio:  IFSP-BR-002
                    descricao: Carteira
                    itemTipo:
                      nome: Sala de aula
                      descricao: Materiais de sala de aula
                      imagem: https://images.unsplash.com/photo-1580582932707-520aed937b7b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80
                    dataAquisicao: '2016-08-29T09:12:33.001Z'
                    precoAquisicao: 999.99
                    departamento: CAE
                    responsavel: 
                        prontuario: BP0910292
                        nome: Luiz Gustavo Véras
                        telefone: 408-867-5309
                        email: gustavo_veras@ifsp.edu.br
                    
                  - patrimonio:  IFSP-BR-003
                    descricao: Bebedouro
                    itemTipo:
                      nome: Infraestrutura
                      descricao: Materiais utilizados em corredores e de infraestrutura
                      imagem: https://images.unsplash.com/photo-1497366754035-f200968a6e72?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80
                    dataAquisicao: '2016-08-29T09:12:33.001Z'
                    precoAquisicao: 999.99
                    departamento: Almoxarifado
                    responsavel: 
                        prontuario: BP0910292
                        nome: Luiz Gustavo Véras
                        telefone: 408-867-5309
                        email: gustavo_veras@ifsp.edu.br
        '400':
          description: bad input parameter
    post:
      summary: Adiciona um novo item ao inventário de almoxarifado
      tags:
        - patrimonio
      description: Adiciona um item ao sistema
      responses:
        '201':
          description: novo item criado
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: Um item com esses dados já existe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemPatrimonio'
        description: Dado de inventario a ser adicionado
  /patrimonio/{id_patrimonio}:
    get:
      summary: Busca o itens do inventário para um patrimônio informado
      tags:
        - patrimonio
      description: |
        O cliente passa um patrimonio registrado para buscar os dados do item correspondente.
      parameters: 
        - in: path
          name: id_patrimonio
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retorno o item para patrimônio informado
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ItemPatrimonio'
        '404':
          description: Item não encontrado para o patrimônio informado
    delete:
      summary: Remove o item com o patrimônio informado
      tags:
        - patrimonio
      description: |
        O cliente passa um patrimonio registrado para buscar os dados do item correspondente.
      parameters: 
        - in: path
          name: id_patrimonio
          description: Patrimonio ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retorno de mensagem removida para patrimônio informado
          content:
            application/text:
              example: Item removido
        '404':
          description: Item não encontrado para o patrimônio informado

components:
  schemas:
    ItemPatrimonio:
      type: object
      required:
        - patrimonio
        - descricao
        - itemTipo
        - dataAquisicao
        - precoAquisicao
        - departamento
        - responsavel
      properties:
        patrimonio:
          type: string
          example: IFSP-BR-001
        descricao:
          type: string
          example: Carteira
        itemTipo:
          $ref: '#/components/schemas/ItemTipo'
        dataAquisicao:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        precoAquisicao:
          type: number
          example: 199.90
        departamento:
          type: string
          example: Informática
        responsavel:
          $ref: '#/components/schemas/Responsavel'
    ItemTipo:
      properties:
        nome:
          type: string
          example: Escritorio
        descricao:
          type: string
          example: Materiais utilizados em escritório
        imagem:
          type: string
          format: url
          example: 'https://images.unsplash.com/photo-1602506860730-b690f1a6f662?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'
    Responsavel:
      properties:
        prontuario:
          type: string
          example: BP0910292
        nome:
          type: string
          example: Luiz Gustavo Véras
        telefone:
          type: string
          example: 408-867-5309
        email:
          type: string
          format: email
          example: gustavo_veras@ifsp.edu.br